subroutine logo

implicit none

WRITE(*,*)'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG'
WRITE(*,*)'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG'
WRITE(*,*)'GGGGGGGGGGGGGGGGG                         TERRSTRUC                             GGGGGGGGGGGGGGGGGG'
WRITE(*,*)'GGGGGGGGGGGGGGGGG                                                               GGGGGGGGGGGGGGGGGG'
WRITE(*,*)'GGGGGGGGGGGGGGGGG                  TERRESTRIAL PLANET STRUCTURE                 GGGGGGGGGGGGGGGGGG'
WRITE(*,*)'GGGGGGGGGGGGGGGGG                      (c)  SHENG JIN, PMO                      GGGGGGGGGGGGGGGGGG'
WRITE(*,*)'GGGGGGGGGGGGGGGGG                  EMAIL: sheng.s.jin@gmail.com                 GGGGGGGGGGGGGGGGGG'
WRITE(*,*)'GGGGGGGGGGGGGGGGG                                                               GGGGGGGGGGGGGGGGGG'
WRITE(*,*)'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG'
WRITE(*,*)'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG'
WRITE(*,*)

RETURN 
end subroutine logo
